// <auto-generated />
using System;
using B1SecondTaskWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B1SecondTaskWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("B1SecondTaskWebAPI.Models.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ActiveDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActiveDecimal2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<decimal>("PassiveDecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PassiveDecimal2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FilesData");
                });

            modelBuilder.Entity("B1SecondTaskWebAPI.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("B1SecondTaskWebAPI.Models.DataModel", b =>
                {
                    b.HasOne("B1SecondTaskWebAPI.Models.FileModel", "File")
                        .WithMany("FilesData")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("B1SecondTaskWebAPI.Models.FileModel", b =>
                {
                    b.Navigation("FilesData");
                });
#pragma warning restore 612, 618
        }
    }
}
